team_translation = {
    "우크라이나": "Ukraine",
    "크로아티아": "Croatia",
    "헝가리": "Hungary",
    "스웨덴": "Sweden",
    "웨일스": "Wales",
    "잉글랜드": "England",
    "오스트리아": "Austria",
    "스코틀랜드": "Scotland",
    "스위스": "Switzerland",
    "슬로바키아": "Slovakia",
    "프랑스": "France",
    "네덜란드": "Netherlands",
    "독일": "Germany",
    "북마케도니아": "North Macedonia",
    "이탈리아": "Italy",
    "벨기에": "Belgium",
    "폴란드": "Poland",
    "터키": "Turkey",
    "핀란드": "Finland",
    "체코": "Czech Republic",
    "러시아": "Russia",
    "포르투갈": "Portugal",
    "덴마크": "Denmark",
    "스페인": "Spain",
    "왓포드": "Watford",
    "리버플": "Liverpool",
    "리즈": "Leeds",
    "토트넘": "Tottenham",
    "애스턴": "Aston Villa",
    "씨티": "Manchester City",
    "번리": "Burnley",
    "팔라스": "Crystal Palace",
    "울버햄프턴": "Wolverhampton",
    "브라이튼": "Brighton",
    "노리치": "Norwich",
    "에버튼": "Everton",
    "뉴케슬": "Newcastle",
    "웨스트햄": "West Ham",
    "이슬링턴": "Arsenal",
    "첼시": "Chelsea",
    "사우샘프턴": "Southampton",
    "유나이티드": "Manchester United",
    "브렌트포드": "Brentford",
    "레스터": "Leicester",
    "캐나다": "Canada",
    "오스트레일리아": "Australia",
    "카타르": "Qatar",
    "가나": "Ghana",
    "이란": "Iran",
    "세르비아": "Serbia",
    "대한민국": "South Korea",
    "에콰도르": "Ecuador",
    "멕시코": "Mexico",
    "미국": "USA",
    "일본": "Japan",
    "사우디아라비아": "Saudi Arabia",
    "우루과이": "Uruguay",
    "모로코": "Morocco",
    "세네갈": "Senegal",
    "케메룬": "Cameroon",
    "브라질": "Brazil",
    "코스타리카": "Costa Rica",
    "아르헨티나": "Argentina",
    "튀니지": "Tunisia"
}

def translate_team(name: str) -> str:
    return team_translation.get(name, name)
